server:
  port: 3189
spring:
  application:
    ##eureka的服务名称
    name: eureka-server
eureka:
  client:
    # 设置是否将自己作为客户端注册到注册中心（缺省true）
    # 这里为不需要（查看@EnableEurekaServer注解的源码，会发现它间接用到了@EnableDiscoveryClient）
    register-with-eureka: true
    fetch-registry: false
    #eureka的地址信息
    service-url:
      defaultZone: http://127.0.0.1:3189/eureka/
